### ISSUE TITLE
update beta backlink in package-info.java

### ISSUE THREAD

**Issue by srl295** [IBM-Bluemix/gp-java-client#9]
https://github.com/IBM-Bluemix/gp-java-client/blob/master/src/main/java/com/ibm/g11n/pipeline/client/package-info.java#L3 links to an old (beta) URL. Probably better to link to this Github repo.

Look for other similar links.

**Comment by yumaoka** [comment]
Committed the fix directly: 9eb4b690e90eb54b49983a2b7d33aeef40defaff
